modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
[[mods]]
modId = "commandconfirm"
version = "${mod_version}"
displayName = "CommandConfirm"
description = ''

[[dependencies.commandconfirm]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.commandconfirm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"
